
# POST http://localhost:3000/auth/signup HTTP/1.1
# content-type: application/json

# {
#     "id": 1234,
#     "nickname": "도영맘3",
#     "password": "abc123",
#     "email": "email@email.com"
# }

POST http://localhost:3000/auth/signin HTTP/1.1
content-type: application/json

{
    "email": "b@email.com",
    "password": "abc123"
}