
# POST http://localhost:3000/auth/signup HTTP/1.1
# content-type: application/json

# {
#     "id": 1234,
#     "nickname": "도영맘3",
#     "password": "abc123",
#     "email": "email@email.com"
# }

# POST http://43.201.105.90:3000/auth/signin HTTP/1.1
# content-type: application/json

# {
#     "email": "c@email.com",
#     "password": "abcd1234"
# }

POST http://localhost:3000/auth/signin2 HTTP/1.1
content-type: application/json

{
    "password": "pass1",
    "email": "user1"
}